spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATASOURCE_URL:jdbc:h2:mem:blog_service;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_ENABLED:true}
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    allowed-origin: ${ALLOWED_ORIGIN:http://localhost:3000}
    csrf:
      enabled: false
    hsts:
      enabled: true
feign:
  client:
    config:
      default:
        loggerLevel: FULL
logging:
  level:
    org.springframework.security: DEBUG
    com.kakao.blog: DEBUG
